logging:
  level:
    root: WARN
    de.stintlab: INFO
management:
  server:
    port: 8090
  endpoints:
    access:
      default: NONE
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      access: READ_ONLY
    prometheus:
      access: READ_ONLY
    probes:
      enbaled: true
spring:
  application:
    name: Centrifuge
  webflux:
    basePath: /v1.0/
  profiles:
    active: local
